/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-11-22 06:44:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1637108553900L));
    _jspx_dependants.put("jar:file:/C:/Users/ITSC/Desktop/SmartWeb/jspstudy/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/11_MYHOME/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>My Home Page</title>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"\n");
      out.write("	integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- \n");
      out.write("\n");
      out.write("	   $('#pwck').on('blur', function(){\n");
      out.write("			if($('#pw').val() == $('#pwck').val()){\n");
      out.write("				alert('비밀번호가 일치 합니다.');\n");
      out.write("			}else if($('pw').val() != $('#pwck').val()){\n");
      out.write("				alert('비밀번호를 다시 확인 해주세요.');\n");
      out.write("				event.prevetDefualt();\n");
      out.write("			}\n");
      out.write("		});	\n");
      out.write("\n");
      out.write(" -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	$(document).ready(function(){\n");
      out.write("		\n");
      out.write("		/* 아이디 중복 체크 */\n");
      out.write("		$('#id').on('keyup', function(){\n");
      out.write("			$.ajax({\n");
      out.write("				url: 'idCheck.member',		\n");
      out.write("				type: 'post',\n");
      out.write("				data: 'id=' + $('#id').val(),\n");
      out.write("				dataType: 'json',\n");
      out.write("				success: function(resData){\n");
      out.write("					if(resData.result == true){\n");
      out.write("						$('#id_check').text('사용 가능한 아이디 입니다.');\n");
      out.write("					}else{\n");
      out.write("						$('#id_check').text('이미 사용중인 아이디 입니다.');\n");
      out.write("					}\n");
      out.write("				},\n");
      out.write("				error: function(xhr){\n");
      out.write("					alert(xlr.responseText);\n");
      out.write("				},\n");
      out.write("			});\n");
      out.write("		});\n");
      out.write("			\n");
      out.write("		/* 비밀번호 재확인 */\n");
      out.write("		$('#f').on('submit', function(event){\n");
      out.write("			if($('#pw').val() != $('#pwck').val()){\n");
      out.write("				alert('비밀번호를 다시 확인 해주세요.');\n");
      out.write("				event.preventDefault();\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("				return true;\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div>\n");
      out.write("		<form id=\"f\" action=\"join.member\" method=\"post\">\n");
      out.write("			<input type=\"text\" name=\"id\" id=\"id\" placeholder=\"ID\">\n");
      out.write("			<span id=\"id_check\"></span><br>\n");
      out.write("			<input type=\"password\" name=\"pw\" id=\"pw\" placeholder=\"PW\"> <br>\n");
      out.write("			<input type=\"password\" name=\"pwck\" id=\"pwck\" placeholder=\"PW Check\"> <br>\n");
      out.write("			<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"NAME\"> <br>\n");
      out.write("			<input type=\"text\" name=\"email\" id=\"email\" placeholder=\"Email\"> <br>\n");
      out.write("			<button>Join</button>\n");
      out.write("			<input type=\"reset\" value=\"Reset\">\n");
      out.write("			<input type=\"button\" value=\"Do Not Join\" onclick=\"location.href='index.jsp'\">\n");
      out.write("		</form>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
