DROP TABLE MEMBERS;
CREATE TABLE MEMBERS
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(32) NOT NULL UNIQUE,
	NAME VARCHAR2(32),
	GRADE VARCHAR2(10) CHECK (GRADE IN('bronze', 'silver', 'gold', 'vip')),
	POINT NUMBER
);

DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ NOCACHE;

INSERT INTO MEMBERS VALUES (MEMBER_SEQ.NEXTVAL, 'jack', '잭', 'vip', 5000);

INSERT INTO MEMBERS VALUES (MEMBER_SEQ.NEXTVAL, 'scott', '스캇', 'gold', 4000);

INSERT INTO MEMBERS VALUES (MEMBER_SEQ.NEXTVAL, 'wolf', '울프', 'bronze', 1000);

INSERT INTO MEMBERS VALUES (MEMBER_SEQ.NEXTVAL, 'eagle', '이글', 'silver', 3500);

INSERT INTO MEMBERS VALUES (MEMBER_SEQ.NEXTVAL, 'prodo', '프로도', 'gold', 4500);

COMMIT